development:
  host: localhost
  database: backbone_twitter_bootstrap_development

test:
  host: localhost
  database: backbone_twitter_bootstrap_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
